CREATE TABLE n1usr
(id int(10) PRIMARY KEY AUTO_INCREMENT, 
name VARCHAR(100),
surname VARCHAR(100),
mdl VARCHAR(100),
birth_day DATETIME);

CREATE TABLE n2catg
(id INT(10) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100),
page INT(10));

CREATE TABLE n3tags
(id INT(10) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100),
cl VARCHAR(100));

CREATE TABLE n4prjc
(id INT(10) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100));

CREATE TABLE n5tsk
(id int(10) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100),
d_st DATETIME,
d_ed DATETIME);
