CREATE TABLE users
(id int(10) PRIMARY KEY AUTO_INCREMENT, 
name VARCHAR(100),
surname VARCHAR(100),
mdl VARCHAR(100),
birth_day DATETIME);

CREATE TABLE category
(id INT(10) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100),
page INT(10));

CREATE TABLE tags
(id INT(10) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100),
cl VARCHAR(100));

CREATE TABLE project
(id INT(10) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100));

CREATE TABLE tasks
(id int(10) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100),
d_st DATETIME,
d_ed DATETIME);
