CREATE TABLE n1u
(id int(10) PRIMARY KEY AUTO_INCREMENT, 
name VARCHAR(100),
surname VARCHAR(100),
birth_day DATETIME);

CREATE TABLE n2p
(id INT(10) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100),
page INT(10));

CREATE TABLE n3t
(id INT(10) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100),
cl VARCHAR(100));

CREATE TABLE n4p
(id INT(10) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100));

CREATE TABLE n5t
(id int(10) PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100),
d_st DATETIME,
d_ed DATETIME);